name: lint, test
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  go-inspect:
    name: Inspect packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
       # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: hu
        run: |
          echo "test"
          VERSION=${{ inputs.generator_version }}
          echo ${VERSION}
      - name: cancel-action
        uses: kuritka/cancel-action@0.0.9
        with:
          verbose: true
#         token: ${{ secrets.REMOVE_WORKFLOW_TOKEN }}

